#!/bin/bash -l
#
#SBATCH --job-name=get_data
#SBATCH --output=job.out
#SBATCH --time=01:00:00
#SBATCH --ntasks=1
#SBATCH  --partition=xfer
module unload xalt

if [ ! -d ../input/output/ifs2lm ] ; then mkdir -p ../input/ifs2lm ;fi
find /project/pr04/ERAinterim/2006/ERAINT_2006_{05..08}.tar.gz -exec tar --transform 's/caf/cas/' -xf {} -C input \;

cp /project/pr04/davidle/results_clim/lm_c/24h/2006/lffd2006050100.nc ../input/lffd2006050100_lm_c.nc
cp /project/pr04/davidle/results_clim/lm_f/24h/2006/lffd2006050100.nc ../input/lffd2006050100_lm_f.nc
cp /project/pr04/extpar-HPC/extp2_EUROPE_MCH_12km.nc ../1_ifs2lm/
cp /project/pr04/extpar-HPC/extpar_2km_europe.nc ../3_lm2lm/

