#!/usr/local/bin/bash -l
#SBATCH --job-name="means"
#SBATCH --time=06:00:00
##SBATCH --time=00:30:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --partition=normal
#SBATCH --constraint=gpu

#Load modules
. /etc/bash.bashrc
module load daint-gpu
module load NCO
module load CDO

#Prevent harmless error
module unload xalt

# Run LM in case directory
 srun -e ${logfiles}/${LM_MODEL}_means_conv.err -o ${logfiles}/${LM_MODEL}_means_conv.out ${BINDIR}/means_conv.sh
