#!/usr/local/bin/bash -l
#SBATCH --job-name="copy_data"
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --partition=xfer

#Prevent harmless error
module unload xalt

# Run LM in case directory
 srun -e copy_data.err -o copy_data.out ../copy_data_to_scratch.sh
