#!/usr/local/bin/bash -l
#SBATCH --job-name="prudence"
#SBATCH --time=24:00:00
#SBATCH --partition=normal
#SBATCH --constraint=gpu

#Prevent harmless error
module unload xalt

# Run LM in case directory
 srun -e ${logfiles}/${LM_MODEL}_prudence.err -o ${logfiles}/${LM_MODEL}_prudence.out ${BINDIR}/prudence.sh
