#!/usr/local/bin/bash -l
#SBATCH --job-name="vw_so_rel"
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --partition=normal
#SBATCH --hint=memory_bound
#SBATCH --mem=64000MB
#SBATCH --constraint=gpu

#Load Modules
. /etc/bash.bashrc
module load daint-gpu
module load PyExtensions
module load netcdf-python
module load NCO

#Prevent harmless error
module unload xalt

#module purge
# Run LM in case directory
 srun -e ${logfiles}/${LM_MODEL}_vw_so_rel.err -o ${logfiles}/${LM_MODEL}_vw_so_rel.out ${BINDIR}/compute_vw_so_rel.sh
