#!/usr/local/bin/bash -l
#SBATCH --job-name="merge"
#SBATCH --time=06:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --partition=normal
#SBATCH --constraint=gpu

#Prevent harmless error
module unload xalt

#Modules
. /etc/bash.bashrc
module load daint-gpu
module load NCO
module load CDO

# Run LM in case directory
 srun -e ${logfiles}/${LM_MODEL}_merge.err -o ${logfiles}/${LM_MODEL}_merge.out ${BINDIR}/merge.sh
