#!/usr/local/bin/bash -l
#SBATCH --job-name="timeseries"
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --partition=normal
#SBATCH --constraint=gpu


module load daint-gpu
module load NCO
module load CDO

#module purge
# Run LM in case directory
 srun -e ${logfiles}/${LM_MODEL}_timeseries.err -o ${logfiles}/${LM_MODEL}_timeseries.out ${BINDIR}/timeseries.sh
