#!/usr/local/bin/bash -l
#SBATCH --job-name="diff"
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --partition=normal
#SBATCH --constraint=gpu

#Prevent harmless error
module unload xalt

# Run LM in case directory
 srun -e ${logfiles}/${LM_MODEL}_differences.err -o ${logfiles}/${LM_MODEL}_differences.out ${BINDIR}/differences.sh
