#!/bin/bash

module load daint-gpu

export ext_data=/project/pr04/extpar-HPC
export bd_data=/project/pr04/ERAinterim
export w_so_dir=$PROJECT/results_clim

# clean away old *.out files
\rm -f *.out 2>/dev/null

# submit job
if [ -z "${WAITFORJOB}" ]; then
  jobid=`sbatch job | sed 's/Submitted batch job //g'`
else
  jobid=`sbatch --dependency=afterok:${WAITFORJOB} job | sed 's/Submitted batch job //g'`
fi

if [ $? -eq 0 -a -n "${jobid}" ]; then
  echo "${jobid}" > .jobid
  echo "${jobid}"
else
  exit 1
fi

