#!/bin/tcsh
#SBATCH --job-name=lm_f
#SBATCH --output=job.out
#SBATCH --nodes=144
#SBATCH --ntasks-per-node=1
#SBATCH --partition=normal
#SBATCH --time=16:00:00
#SBATCH --account=pr04
#SBATCH --constraint=gpu
module load daint-gpu
setenv CRAY_CUDA_MPS 1

# Initialization
set verbose
set echo

# set environmental parameters
setenv OMP_NUM_THREADS 1
setenv COSMO_NPROC_NODEVICE 0
setenv MALLOC_MMAP_MAX_ 0
setenv MALLOC_TRIM_THRESHOLD_ 536870912
setenv MV2_ENABLE_AFFINITY 0
setenv MV2_USE_CUDA 1
setenv MPICH_RDMA_ENABLED_CUDA 1
setenv MPICH_G2G_PIPELINE 256
setenv CRAY_CUDA_PROXY 0
setenv CUDA_VA_RESERVATION_CHUNK_SIZE 4294967296
setenv CRAY_TCMALLOC_MEMFS_FORCE 1

#Replace soil moisture field
module load NCO
module load PyExtensions/3.5-CrayGNU-17.08 
module load netcdf-python/1.2.9-CrayGNU-17.08-python-3

python3 ~/analysis_soilmoistre_pertubation_10a/perturb_soil-water_potential_local.py ../../ctrl/output/lm2lm/laf2006070100.nc ~/postproc_data/SOILTYP_lm_f.nc ./input/W_SO_2006070100.nc -0.3 ~/postproc_data/fr_land_WestAlps_lm_f.nc
ncks -v W_SO ./input/W_SO_2006070100.nc -A ./input/laf2006070100.nc

# cleanup
./clean

# echo date
date

# Run LM in case directory
srun -u -n 144 ./lm_f90

# echo date
date

# do postprocessing
cd ./output/
../../bin/grc
cd -

# remove job tag (if present)
\rm -f .jobid >&/dev/null

# done
