#!/bin/tcsh
#SBATCH --job-name=lm2lm
#SBATCH --output=job.out
#SBATCH --ntasks=22
#SBATCH --partition=normal
#SBATCH --time=24:00:00
#SBATCH --account=pr04
#SBATCH --constraint=gpu
module load daint-gpu
#SBATCH --hint=nomultithread

# Initialization
set verbose
set echo

# set environmental parameters
setenv OMP_NUM_THREADS 1
setenv MALLO 0
setenv MALLOC_TRIM_THRESHOLD_ 536870912
setenv MPICH_RDMA_ENABLED_CUDA 0
setenv MV2_USE_CUDA 0

# cleanup
./clean

# echo date
date

# Run LM in case directory
srun -n 22 ./int2lm

# echo date
date

# do postprocessing
cd ./output/
../../bin/grc
cd -

# remove job tag (if present)
\rm -f .jobid >&/dev/null

# done
